# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Motolani Akala (cbe60484-2e3a-4e0c-a004-065611439137)'
    subscriptionId: 'cbe60484-2e3a-4e0c-a004-065611439137'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Mofolawe'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Mendore85/ARM-Test'
    deploymentMode: 'Incremental'
